name: Xcode - Build and Test

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-test:
    name: Build and Test iOS Sprite Game
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Default Scheme
        run: |
          # Retrieve the scheme list in JSON, extract the first target as the default scheme
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo "$default" > default_scheme
          echo "Using default scheme: $default"
          echo "DEFAULT_SCHEME=$default" >> $GITHUB_ENV

      - name: Build
        env:
          scheme: ${{ env.DEFAULT_SCHEME }}
        run: |
          # Read scheme if not provided explicitly
          if [ -z "$scheme" ]; then scheme=$(cat default_scheme); fi
          echo "Building with scheme: $scheme"

          # Determine whether to build using workspace or project file
          if [ -n "$(find . -maxdepth 1 -name '*.xcworkspace' -print -quit)" ]; then 
            filetype_parameter="workspace"
            file_to_build=$(find . -maxdepth 1 -name "*.xcworkspace" | head -n 1)
          else 
            filetype_parameter="project"
            file_to_build=$(find . -maxdepth 1 -name "*.xcodeproj" | head -n 1)
          fi

          echo "Building $filetype_parameter: $file_to_build"

          # Clean, build, and analyze using the determined file
          xcodebuild clean build analyze -scheme "$scheme" -"$filetype_parameter" "$file_to_build" | xcpretty
          exit ${PIPESTATUS[0]}

      - name: Test
        env:
          scheme: ${{ env.DEFAULT_SCHEME }}
        run: |
          if [ -z "$scheme" ]; then scheme=$(cat default_scheme); fi
          echo "Testing with scheme: $scheme"

          if [ -n "$(find . -maxdepth 1 -name '*.xcworkspace' -print -quit)" ]; then 
            filetype_parameter="workspace"
            file_to_build=$(find . -maxdepth 1 -name "*.xcworkspace" | head -n 1)
          else 
            filetype_parameter="project"
            file_to_build=$(find . -maxdepth 1 -name "*.xcodeproj" | head -n 1)
          fi

          echo "Testing $filetype_parameter: $file_to_build"

          # Run tests on a simulator (using a more recent iOS version)
          xcodebuild test -scheme "$scheme" -"$filetype_parameter" "$file_to_build" \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' | xcpretty
          exit ${PIPESTATUS[0]}
